nearbyservices/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('serviceproviders.urls')),
]

serviceproviders/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('serviceproviderregistration/', views.register_service_provider, name='register_service_provider'),
    path('login/', views.login_view, name='login'),
    path('serviceprovider/', views.service_provider_latest_service, name='service_provider_services'),
    path('serviceproviderprofile/<int:pk>/', views.serviceproviderprofile,name='serviceproviderprofile'),
    path('submit_feedback/', views.submit_feedback, name='submit_feedback'),
    path('logout/', views.logout_view, name='logout'),

]

#Serving static during development only
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

serviceproviders/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.hashers import make_password
from PIL import Image  # Import the Image class from Pillow
from moviepy.editor import VideoFileClip

class CustomUser(AbstractUser):
    username = models.CharField(max_length=100, unique=False)
    email = models.EmailField(unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        # Hash the password before saving
        if self.password and not self.password.startswith('pbkdf2_sha256$'):
            self.password = make_password(self.password)
        super(CustomUser, self).save(*args, **kwargs)

class Service(models.Model):
    service_name = models.CharField(max_length=100)
    service_charge = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    service_video = models.FileField(upload_to='service_videos/', null=True, blank=True)
    service_picture = models.FileField(upload_to='service_pictures/', null=True, blank=True)
    service_description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.service_name

class ServiceProvider(models.Model):
    user_as_a_provider = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pictures', null=True, blank=True)
    location = models.CharField(max_length=20)
    services_provided = models.ManyToManyField(Service, blank=True)  # Establish a many-to-many relationship with Service

    def __str__(self):
        return f"{self.user_as_a_provider.username}"

class ClientFeedback(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)  # ForeignKey to associate feedback with a specific service
    client_feedback = models.TextField()

    def __str__(self):
        return self.client_feedback

class Logo(models.Model):
    logo = models.ImageField(upload_to='logoimage', null=True, blank=True)

serviceproviders/forms.py
from django import forms
from .models import CustomUser, ServiceProvider, Service

'''

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'username'}),
            'email': forms.EmailInput(attrs={'class': 'email'}),
            'password': forms.PasswordInput(attrs={'class': 'password'}),
        }


    password2 = forms.CharField(required=True, label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'password2'}))

    def clean_password2(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match.")

        return password1
    


    profile_picture = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'profile_picture'}))
    location = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'location'}))
    service_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'service_name '}))
    service_charge = forms.DecimalField(max_digits=8, decimal_places=2, widget=forms.TextInput(attrs={'class': 'service_charge'}))
    service_video = forms.FileField(required=False, widget=forms.FileInput(attrs={'class': 'service_video'}))
    service_picture = forms.FileField(required=False, widget=forms.FileInput(attrs={'class': 'service_picture'}))
    service_description = forms.CharField(widget=forms.Textarea(attrs={'class': 'service_description'}), required=False)

    def save(self, commit=True):
        if not self.is_valid():
            raise ValueError("Form is not valid. Cannot save.")

        # Create a CustomUser instance and set the user's attributes
        custom_user = super().save(commit=False)
        custom_user.set_password(self.cleaned_data['password'])

        # Create a ServiceProvider instance linked to the user
        service_provider = ServiceProvider(user_as_a_provider=custom_user) #This line creates a new ServiceProvider instance and associates it with the user specified by the custom_user instance.
        service_provider.location = self.cleaned_data['location']
        service_provider.profile_picture = self.cleaned_data['profile_picture']

        service = Service(
            service_name=self.cleaned_data['service_name'],
            service_charge=self.cleaned_data['service_charge'],
            service_video=self.cleaned_data['service_video'],
            service_picture=self.cleaned_data['service_picture'],
            service_description=self.cleaned_data['service_description']
        )

        if commit:
            custom_user.save()
            service_provider.save()
            service.save()
            service_provider.services_provided.add(service) # this line adds the FIRST SERVICE, to a list of services provided by the service provider

        return custom_user
    
'''





from django import forms

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'username'}))
    email = forms.EmailField( widget=forms.EmailInput(attrs={'class': 'email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'password2'}))
    profile_picture = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'profile_picture'}))
    location = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'service_name'}))
    service_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'location'}))
    service_charge = forms.DecimalField(max_digits=8, decimal_places=2, widget=forms.TextInput(attrs={'class': 'service_charge'}))
    service_video = forms.FileField(required=False, widget=forms.FileInput(attrs={'class': 'service_video'}))
    service_picture = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'service_picture'}))
    service_description = forms.CharField(widget=forms.Textarea(attrs={'class': 'service_description'}), required=False)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password and password2 and password != password2:
            self.add_error('password2', "Passwords do not match")

        return cleaned_data








class CustomUserLoginForm(forms.Form):
    email = forms.EmailField(label='Email', required=True, widget=forms.EmailInput(attrs={'class': 'email'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'password'}), required=True)

serviceproviders/views.py
import os
from io import BytesIO
from django.core.files.base import ContentFile
from PIL import Image
from moviepy.editor import VideoFileClip

from .forms import RegistrationForm, CustomUserLoginForm
from django.contrib.auth import login, authenticate,logout
from django.shortcuts import render,redirect
from .models import Logo,ServiceProvider, Service,CustomUser,ClientFeedback
from django.db import transaction
from django.views.decorators.http import require_POST
from PIL import Image
from moviepy.editor import VideoFileClip


def home(request):
    latest_logo = Logo.objects.order_by('-pk').first()
    service_providers = ServiceProvider.objects.all()
    context ={'logo': latest_logo,'service_providers':service_providers}
    return render(request, 'serviceproviders\home.html',context)

def service_provider_latest_service(request):
    service_providers = ServiceProvider.objects.all()
    context ={'service_providers':service_providers}
    return render(request, 'serviceproviders/home.html', context)


@require_POST
def submit_feedback(request):
    service_id = request.POST.get('service_id')
    client_feedback_text = request.POST.get('client_feedback')
    service = Service.objects.get(id=service_id)
    
    # Get the authenticated user's username or 'Anonymous' for anonymous users
    user_username = request.user.username if request.user.is_authenticated else 'Anonymous'
    
    if client_feedback_text:
        feedback = ClientFeedback(service=service, client_feedback=f" {user_username}: {client_feedback_text}")
        feedback.save()
        return redirect('home')

    return render(request, 'serviceproviders\home.html')

def serviceproviderprofile(request,pk):
    service_providers = ServiceProvider.objects.get(pk=pk)
    
    context={'service_providers': service_providers}


    return render(request, 'serviceproviders\profile.html',context)

def service_detail(request,pk):
    # Retrieve the specific service and its client feedback
    service = Service.objects.get(pk=pk)
    feedback = ClientFeedback.objects.filter(service=service)

    context = {
        'service': service,
        'feedback': feedback,
    }

    return render(request, 'service_detail.html', context)










def compress_video(video_file, width=640):
    # Load the video using VideoFileClip
    video = VideoFileClip(video_file)
    # Resize the video width to the specified value
    video = video.resize(width=width)
    
    # Save the compressed video to an in-memory file
    with BytesIO() as output_buffer:
        video.write_videofile(output_buffer, codec='libx264')
        compressed_video = ContentFile(output_buffer.getvalue())
    
    return compressed_video
from moviepy.editor import VideoFileClip


def register_service_provider(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)

        if form.is_valid():
            # Extract data from the form
            with transaction.atomic():
                
                # Extract data from the form
                username = form.cleaned_data['username']
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']
                profile_picture = form.cleaned_data['profile_picture']
                location = form.cleaned_data['location']
                service_name = form.cleaned_data['service_name']
                service_charge = form.cleaned_data['service_charge']
                service_video = form.cleaned_data['service_video']
                service_picture = form.cleaned_data['service_picture']
                service_description = form.cleaned_data['service_description']

                # Create user instance
                user = CustomUser(username=username, email=email)
                user.set_password(password)
                user.save()


                #if service_video:
                    #service_video = compress_video(service_video)

                # Create service instance
                service = Service.objects.create(
                    service_name=service_name,
                    service_charge=service_charge,
                    service_video=service_video,
                    service_picture=service_picture,
                    service_description=service_description
                )

                # Create service provider
                provider = ServiceProvider.objects.create(
                    user_as_a_provider=user,
                    profile_picture=profile_picture,
                    location=location
                )

                # Add the service to the provider using .set()
                provider.services_provided.set([service])

                return redirect('home')  # Redirect to a success page if everything is successful

    else:
        form = RegistrationForm()

    return render(request, 'serviceproviders\service_provider_registration.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = CustomUserLoginForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                # Redirect to a success page or do something else
                return redirect('home')
    else:
        form = CustomUserLoginForm()

    return render(request, 'serviceproviders\login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('home')

serviceproviders/templates/serviceproviders/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>

      main{
        background-color: rgb(245, 247, 228);
        margin-top: 220px;
      }

      .eachprovider{
            background-color: #fff;
            border: 1px solid #858282;
            border-radius: 5px;
            margin: 5px;
            box-shadow: 0 2px 2px rgba(75, 75, 75, 0.1);
      }

      .providerinfo{
        display: flex;
        gap: 50px;
        background-color: #fff;
        border: 1px solid #eeecec;
        box-shadow: 0 2px 4px rgba(160, 158, 158, 0.1);
      }

      .providerinfo p:nth-child(1) {
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        font-weight: 600;
        font-size: large;
        margin-top: 10px;
      }

      .providerinfo p:nth-child(2){
        font-size: large;
        font-style: italic;
        margin-top: 10px;
      }

      .serviceinfo{
        display: flex;
        gap: 50px;
        font-family: Arial, sans-serif;
      }

      .service_video,.service_picture{
        width: 100%;
      }

      .servicemedia p{
        font-family: Arial, Helvetica, sans-serif;
        font-size: large;
      }

       /* Css to controw visibility of feedback using javascript */
      .feedback-container {
          display: none;
      }

  



    </style>
</head>
<body>
    <div>
        {% include "header.html" %}
    </div>

    <main>
        
          {% for provider in service_providers %}
            <div class="eachprovider">
                <div class="providerinfo">
                    <p> <a href="{% url 'serviceproviderprofile' provider.pk %}">{{ provider.user_as_a_provider.username }}</a></p>
                    <p>Location: {{ provider.location }}</p>
                </div>
          
              {% with last_service=provider.services_provided.last %}
                    {% if last_service %}
                        <div class="serviceinfo">
                            <p>{{ last_service.service_name }}</p>
                            <p> Charges: Ksh{{ last_service.service_charge }}</p>
                        </div>
            
                        
                        <div class="servicemedia">
                          {% if last_service.service_video %}
                            <video src="{{ last_service.service_video.url }}" controls class="service_video"  loading="lazy"></video>
                          {% elif last_service.service_picture %}
                            <img src="{{ last_service.service_picture.url }}" alt="Service Picture" class="service_picture"  loading="lazy">
                          {% endif %}
                          <p>{{ last_service.service_description }}</p>
                        </div>

                        
                        <button class="feedbacks" onclick="toggleFeedbacks(this, 'feedback-container')">Feedbacks</button>
                        <div class="feedback-container">
                          <form method="post" action="{% url 'submit_feedback' %}" class="feedback form">
                            {% csrf_token %}
                            <input type="hidden" name="service_id" value="{{ last_service.id }}">
                            <textarea name="client_feedback" placeholder="Leave your feedback here"></textarea>
                            <input type="submit" value="Submit Feedback">
                        </form>
                        
                        
                        {% for feedback in last_service.clientfeedback_set.all %}
                            <div class="feedback">
                                <p>{{ feedback.client_feedback }}</p>
                            </div>
                        {% endfor %}
                        </div>

                    {% endif %}
              {% endwith %}
            </div>
          {% endfor %}
    </main>




    <div>
        {% include "footer.html" %}
    </div>
</body>

<script>
// feedback.js

function toggleFeedbacks(button, containerClass) {
  // Find the associated feedback container using the provided class
  const feedbackContainer = button.nextElementSibling;
  
  // Toggle the visibility of the feedback container
  if (feedbackContainer.style.display === "none" || feedbackContainer.style.display === "") {
    feedbackContainer.style.display = "block";
  } else {
    feedbackContainer.style.display = "none";
  }
}


</script>
</html>

serviceproviders/templates/serviceproviders/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            text-align: center;
        }

        h1 {
            color: #333;
        }

        form {
            background-color: #fff;
            max-width: 300px;
            margin: 0 auto;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

      

        .email,.password {
            width: 100%;
            padding: 10px  0 10px 0;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        button {
            background-color: #007BFF;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 3px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</body>
</html>

serviceproviders/templates/serviceproviders/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
    .profilepic {
        max-width: 80px;
        height: auto;
        border-radius: 50%;}
    </style>
</head>
<body>
    <h1>Service Provider Profile</h1>
    
    <h2>{{ service_providers.user_as_a_provider.username }}</h2>
    <p>Location: {{ service_providers.location }}</p>
    
    <!-- Display the profile picture -->
    {% if service_providers.profile_picture %}
        <img src="{{ service_providers.profile_picture.url }}" alt="Profile Picture">
    {% else %}
        <p>No profile picture available</p>
    {% endif %}
    
    <h3>Services Provided</h3>
    <ul>
        {% for service in service_providers.services_provided.all %}
            <li>{{ service.service_name }} - ${{ service.service_charge }}</li>
            <p>{{ service.service_description }}</p>
            
            <!-- Display the service video if available -->
            {% if service.service_video %}
                <video controls>
                    <source src="{{ service.service_video.url }}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            {% endif %}
            
            <!-- Display the service picture if available -->
            {% if service.service_picture %}
                <img src="{{ service.service_picture.url }}" alt="Service Picture">
            {% endif %}
        {% endfor %}
    </ul>
    
    <h3>Client Feedback</h3>
    <ul>
        {% for feedback in service_providers.clientfeedback_set.all %}
            <li>{{ feedback.client_feedback }}</li>
        {% endfor %}
    </ul>
</body>
</html>

serviceproviders/templates/serviceproviders/service_provider_registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>serviceprovider registration</title>
    <style>
/* styles.css */
body {
    background-color: #f2f2f2;
    font-family: Arial, sans-serif;
}

.main {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 20px;
    margin: 0 auto;
    max-width: 400px;
}

.formheading {
    text-align: center;
    width: 100%;
    font-size: 24px;
    color: #333;
    margin-bottom: 20px;
}

.serviceproviderregistration {
    background-color: #fff;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
    padding: 20px;
    width: 100%;
}

input[type="text"],
input[type="email"],
input[type="password"],
input[type="file"],
textarea {
    width: 100%;
    padding: 10px  0 10px 0;
    margin: 10px 0;
    border: 1px solid #ccc;
    border-radius: 5px;
    font-size: 16px;
    transition: border 0.3s;
}

input[type="text"]:focus,
input[type="email"]:focus,
input[type="password"]:focus,
input[type="file"]:focus,
textarea:focus {
    border: 1px solid #007bff;
    outline: none;
}

.register-button {
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 5px;
    padding: 10px 20px;
    font-size: 18px;
    cursor: pointer;
    transition: background-color 0.3s;
}

.register-button:hover {
    background-color: #0056b3;
}

    </style>
</head>
<body>
    <main class="main">
        <h2 class="formheading">Service Provider Registration</h2>
    
        <form class="serviceproviderregistration" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Register</button>
        </form>
    </main>
</body>
</html>